package com.mazenet.mani.guruguberasnehabindu.Model

data class TenantDet(val id : Int,
                     val chit_fund_name : String,
                     val company_logo : String,
                     val receipts_logo : String,
                     val favicon : String,
                     val header_name : String,
                     val admin_email : String,
                     val admin_password : String,
                     val gst_no : String,
                     val authorized_person_name : String,
                     val phone_no : String,
                     val mobile_no : Int,
                     val is_new_database : Int,
                     val database_name : String,
                     val slag_url : String,
                     val created_at : String,
                     val created_by : Int,
                     val updated_at : String,
                     val updated_by : Int,
                     val deleted_at : String,
                     val deleted_by : Int,
                     val deletion_remark : Int,
                     val status : Int,
                     val no_branches : Int,
                     val no_groups : Int,
                     val no_users : Int,
                     val no_customers : Int,
                     val start_date : String,
                     val renewal_date : String,
                     val version : String,
                     val sms_enable : Int,
                     val online_bidding_enable : Int,
                     val domain_name : String
)
